<a href="https://colab.research.google.com/github/gmayank9999/DeepLearning/blob/main/Neural_Networks_from_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
# single neuron with 3 inputs
inputs=[1,2,3]
weights=[0.2,0.8,-0.5]
bias=2

output=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+bias
output

2.3

In [26]:
# 3 neurons
# 4 inputs to each neuron with 3 different list of weights
# 3 different bias
#bias and weights are with respect to neuron
inputs=[1,2,3,2.5]

weights1=[0.2,0.8,-0.5,1.0]
weights2=[0.5,-0.91,0.26,-0.5]
weights3=[-0.26,-0.27,0.17,0.87]

bias1=2
bias2=3
bias3=0.5

output=[inputs[0]*weights1[0]+inputs[1]*weights1[1]+inputs[2]*weights1[2]+inputs[3]*weights1[3]+bias1,
        inputs[0]*weights2[0]+inputs[1]*weights2[1]+inputs[2]*weights2[2]+inputs[3]*weights2[3]+bias2,
        inputs[0]*weights3[0]+inputs[1]*weights3[1]+inputs[2]*weights3[2]+inputs[3]*weights3[3]+bias3]
output

#by tweaking the weights and the bias, we can change the output
# hence in deep learning our job is how best to tune the weights and biases

[4.8, 1.21, 2.385]

In [1]:
inputs=[1,2,3,2.5]

weights=[[0.2,0.8,-0.5,1.0],
        [0.5,-0.91,0.26,-0.5],
        [-0.26,-0.27,0.17,0.87]]

biases=[2,3,0.5]

layer_outputs=[]
for neuron_weights,neuron_bias in zip(weights,biases):
    neuron_output=0
    for n_input,weight in zip(inputs,neuron_weights):
      neuron_output+=n_input*weight
    neuron_output+=neuron_bias
    layer_outputs.append(neuron_output)

print(layer_outputs )

[4.8, 1.21, 2.385]


In [3]:
import numpy as np
inputs=[1,2,3,2.5]
weights=[0.2,0.8,-0.5,1.0]
bias=2

output=np.dot(weights,inputs)+bias
print(output)

4.8


In [4]:
import numpy as np
inputs=[1,2,3,2.5]
weights=[[0.2,0.8,-0.5,1.0],
        [0.5,-0.91,0.26,-0.5],
        [-0.26,-0.27,0.17,0.87]]
biases=[2,3,0.5]

output=np.dot(weights,inputs)+biases
print(output)

[4.8   1.21  2.385]


In [4]:
#taking batches of inputs
import numpy as np
inputs=[[1,2,3,2.5],
        [2,5,-1,2],
        [-1.5,2.7,3.3,-0.8]]

weights=[[0.2,0.8,-0.5,1.0],
        [0.5,-0.91,0.26,-0.5],
        [-0.26,-0.27,0.17,0.87]]
biases=[2,3,0.5]

output=np.dot(inputs,np.array(weights).T)+biases
print(output)


[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [6]:
#Working with 2 layers
import numpy as np
inputs=[[1,2,3,2.5],
        [2,5,-1,2],
        [-1.5,2.7,3.3,-0.8]]

weights=[[0.2,0.8,-0.5,1.0],
        [0.5,-0.91,0.26,-0.5],
        [-0.26,-0.27,0.17,0.87]]
biases=[2,3,0.5]

weights2=[[0.1,-0.14,0.5],
        [-0.5,0.12,-0.33],
        [-0.44,0.73,-0.13]]
biases2=[-1,2,-0.5]

layer1_output=np.dot(inputs,np.array(weights).T)+biases
layer2_output=np.dot(layer1_output,np.array(weights2).T)+biases2
print(layer2_output)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [10]:
import numpy as np
# X is the input feature
X=[[1,2,3,2.5],
    [2,5,-1,2],
    [-1.5,2.7,3.3,-0.8]]

class Layer_Dense:
  def __init__(self,n_inputs,n_neurons):
     self.weights=0.10*np.random.randn(n_inputs,n_neurons)
     self.biases=np.zeros((1,n_neurons))
  def forward(self,inputs):
      self.output=np.dot(inputs,self.weights)+self.biases

layer1=Layer_Dense(4,5)
layer2=Layer_Dense(5,2)

layer1.forward(X)
print(layer1.output)

layer2.forward(layer1.output)
print(layer2.output)

[[-0.16205863 -0.59162673 -0.13950288  0.46799897  0.9523419 ]
 [-1.02098302  0.42447985 -0.44718963  0.33623429  1.16785186]
 [ 0.34360369 -0.19537749 -0.32067728 -0.12589691  0.15467134]]
[[-0.06160484 -0.16063992]
 [-0.15447482 -0.26389604]
 [-0.01831633  0.04863493]]


In [11]:
pip install nnfs

In [14]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()
X, y = spiral_data(100, 3)

class Layer_Dense:
  def __init__(self,n_inputs,n_neurons):
     self.weights=0.10*np.random.randn(n_inputs,n_neurons)
     self.biases=np.zeros((1,n_neurons))
  def forward(self,inputs):
      self.output=np.dot(inputs,self.weights)+self.biases

class Activation_ReLU:
  def forward(self,inputs):
    self.output=np.maximum(0,inputs)

layer1 = Layer_Dense(2,5)
activation1 = Activation_ReLU()
layer1.forward(X)
print(layer1.output)
print("="*100)
activation1.forward(layer1.output)
print(activation1.output)


[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [-8.35815910e-04 -7.90404272e-04 -1.33452227e-03  4.65504505e-04
   4.56846210e-05]
 [-2.39994470e-03  5.93469958e-05 -2.24808278e-03  2.03573116e-04
   6.10024377e-04]
 ...
 [ 1.13291524e-01 -1.89262271e-01 -2.06855070e-02  8.11079666e-02
  -6.71350807e-02]
 [ 1.34588361e-01 -1.43197834e-01  3.09493970e-02  5.66337556e-02
  -6.29687458e-02]
 [ 1.07817926e-01 -2.00809643e-01 -3.37579325e-02  8.72561932e-02
  -6.81458861e-02]]
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 4.65504505e-04
  4.56846210e-05]
 [0.00000000e+00 5.93469958e-05 0.00000000e+00 2.03573116e-04
  6.10024377e-04]
 ...
 [1.13291524e-01 0.00000000e+00 0.00000000e+00 8.11079666e-02
  0.00000000e+00]
 [1.34588361e-01 0.00000000e+00 3.09493970e-02 5.66337556e-02
  0.00000000e+00]
 [1.07817926e-01 0.00000000e+00 0.00000000e+00 8.72561932e-02
  0.00000000e+00]

In [17]:
#Input--> Exponentiate --> Normalise --> Output
#Softmax Activation =Exponentiate + Normalise
import numpy as np
# import math

layer_outputs=[4.8,1.21,2.385]
# E=math.e  # E is euler's number =2.7128.....

exp_values=np.exp(layer_outputs)
print(exp_values)

norm_values=exp_values/np.sum(exp_values)
print(norm_values)
print(np.sum(norm_values))

[121.51041752   3.35348465  10.85906266]
[0.89528266 0.02470831 0.08000903]
0.9999999999999999


In [20]:
#Input--> Exponentiate --> Normalise --> Output
#Softmax Activation =Exponentiate + Normalise
#input in batches
layer_outputs=[[4.8,1.21,2.385],
               [8.9,-1.81,0.2],
               [1.41,1.051,0.026]]

exp_values=np.exp(layer_outputs)

# print(np.sum(exp_values,axis=1,keepdims=True))   #axis=0 gives the sum of columns while axis=1 gives the sum of rows which is what we want
norm_values=exp_values/np.sum(exp_values,axis=1,keepdims=True)
print(norm_values)

#Note--> e to the power a large number can lead to overflow error, hence we should subtract the maximum value from all the data points, this will cause no change to the o/p but will protect from the overflow

[[8.95282664e-01 2.47083068e-02 8.00090293e-02]
 [9.99811129e-01 2.23163963e-05 1.66554348e-04]
 [5.13097164e-01 3.58333899e-01 1.28568936e-01]]


In [23]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data


class Layer_Dense:
  def __init__(self,n_inputs,n_neurons):
     self.weights=0.10*np.random.randn(n_inputs,n_neurons)
     self.biases=np.zeros((1,n_neurons))
  def forward(self,inputs):
      self.output=np.dot(inputs,self.weights)+self.biases

class Activation_ReLU:
  def forward(self,inputs):
    self.output=np.maximum(0,inputs)

class Activation_Softmax:
  def forward(self,inputs):
    exp_values=np.exp(inputs-np.max(inputs,axis=1,keepdims=True))
    probabilities=exp_values/np.sum(exp_values,axis=1,keepdims=True)
    self.output=probabilities


X,y=spiral_data(samples=100,classes=3)
dense1=Layer_Dense(2,3)
activation1=Activation_ReLU()

dense2=Layer_Dense(3,3)
activation2=Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)
dense2.forward(activation1.output)
activation2.forward(dense2.output)
print(activation2.output)


[[0.33333334 0.33333334 0.33333334]
 [0.33337906 0.33331284 0.33330804]
 [0.33339453 0.3333061  0.3332993 ]
 [0.3335186  0.33324987 0.33323154]
 [0.3334388  0.33328655 0.3332746 ]
 [0.3335358  0.33324292 0.33322126]
 [0.33360627 0.33321124 0.33318245]
 [0.3337713  0.33313632 0.3330924 ]
 [0.33378714 0.3331297  0.33308312]
 [0.33378202 0.3331324  0.33308554]
 [0.33368942 0.33317465 0.33313596]
 [0.33399874 0.33303437 0.3329669 ]
 [0.33401024 0.33302087 0.33296886]
 [0.33408633 0.33299536 0.33291835]
 [0.3341989  0.33294323 0.3328579 ]
 [0.33426663 0.33291283 0.33282056]
 [0.3341416  0.33294335 0.33291498]
 [0.33438173 0.33286196 0.33275628]
 [0.33334744 0.33332545 0.33332714]
 [0.3344966  0.33281046 0.33269295]
 [0.33451894 0.33279783 0.33268327]
 [0.33380824 0.333068   0.33312374]
 [0.33406496 0.33292454 0.33301046]
 [0.3336738  0.3331431  0.33318308]
 [0.33439115 0.3327962  0.33281267]
 [0.33402696 0.33294576 0.33302724]
 [0.33386466 0.33303645 0.3330989 ]
 [0.33333334 0.33333334 0.33

In [25]:
#Categorical Cross Entropy for Loss Function

import math

softmax_output=[0.7,0.1,0.2]
target_output=[1,0,0]
loss=-(math.log(softmax_output[0])*target_output[0]+
       math.log(softmax_output[1])*target_output[1]+
       math.log(softmax_output[2])*target_output[2])
print(loss)
loss=-math.log(softmax_output[0])
print(loss)


0.35667494393873245
0.35667494393873245
