<a href="https://colab.research.google.com/github/gmayank9999/DeepLearning/blob/main/Neural_Networks_from_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
# single neuron with 3 inputs
inputs=[1,2,3]
weights=[0.2,0.8,-0.5]
bias=2

output=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+bias
output

2.3

In [26]:
# 3 neurons
# 4 inputs to each neuron with 3 different list of weights
# 3 different bias
#bias and weights are with respect to neuron
inputs=[1,2,3,2.5]

weights1=[0.2,0.8,-0.5,1.0]
weights2=[0.5,-0.91,0.26,-0.5]
weights3=[-0.26,-0.27,0.17,0.87]

bias1=2
bias2=3
bias3=0.5

output=[inputs[0]*weights1[0]+inputs[1]*weights1[1]+inputs[2]*weights1[2]+inputs[3]*weights1[3]+bias1,
        inputs[0]*weights2[0]+inputs[1]*weights2[1]+inputs[2]*weights2[2]+inputs[3]*weights2[3]+bias2,
        inputs[0]*weights3[0]+inputs[1]*weights3[1]+inputs[2]*weights3[2]+inputs[3]*weights3[3]+bias3]
output

#by tweaking the weights and the bias, we can change the output
# hence in deep learning our job is how best to tune the weights and biases

[4.8, 1.21, 2.385]

In [1]:
inputs=[1,2,3,2.5]

weights=[[0.2,0.8,-0.5,1.0],
        [0.5,-0.91,0.26,-0.5],
        [-0.26,-0.27,0.17,0.87]]

biases=[2,3,0.5]

layer_outputs=[]
for neuron_weights,neuron_bias in zip(weights,biases):
    neuron_output=0
    for n_input,weight in zip(inputs,neuron_weights):
      neuron_output+=n_input*weight
    neuron_output+=neuron_bias
    layer_outputs.append(neuron_output)

print(layer_outputs )

[4.8, 1.21, 2.385]


In [3]:
import numpy as np
inputs=[1,2,3,2.5]
weights=[0.2,0.8,-0.5,1.0]
bias=2

output=np.dot(weights,inputs)+bias
print(output)

4.8


In [4]:
import numpy as np
inputs=[1,2,3,2.5]
weights=[[0.2,0.8,-0.5,1.0],
        [0.5,-0.91,0.26,-0.5],
        [-0.26,-0.27,0.17,0.87]]
biases=[2,3,0.5]

output=np.dot(weights,inputs)+biases
print(output)

[4.8   1.21  2.385]


In [4]:
#taking batches of inputs
import numpy as np
inputs=[[1,2,3,2.5],
        [2,5,-1,2],
        [-1.5,2.7,3.3,-0.8]]

weights=[[0.2,0.8,-0.5,1.0],
        [0.5,-0.91,0.26,-0.5],
        [-0.26,-0.27,0.17,0.87]]
biases=[2,3,0.5]

output=np.dot(inputs,np.array(weights).T)+biases
print(output)


[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [6]:
#Working with 2 layers
import numpy as np
inputs=[[1,2,3,2.5],
        [2,5,-1,2],
        [-1.5,2.7,3.3,-0.8]]

weights=[[0.2,0.8,-0.5,1.0],
        [0.5,-0.91,0.26,-0.5],
        [-0.26,-0.27,0.17,0.87]]
biases=[2,3,0.5]

weights2=[[0.1,-0.14,0.5],
        [-0.5,0.12,-0.33],
        [-0.44,0.73,-0.13]]
biases2=[-1,2,-0.5]

layer1_output=np.dot(inputs,np.array(weights).T)+biases
layer2_output=np.dot(layer1_output,np.array(weights2).T)+biases2
print(layer2_output)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [10]:
import numpy as np
# X is the input feature
X=[[1,2,3,2.5],
    [2,5,-1,2],
    [-1.5,2.7,3.3,-0.8]]

class Layer_Dense:
  def __init__(self,n_inputs,n_neurons):
     self.weights=0.10*np.random.randn(n_inputs,n_neurons)
     self.biases=np.zeros((1,n_neurons))
  def forward(self,inputs):
      self.output=np.dot(inputs,self.weights)+self.biases

layer1=Layer_Dense(4,5)
layer2=Layer_Dense(5,2)

layer1.forward(X)
print(layer1.output)

layer2.forward(layer1.output)
print(layer2.output)

[[-0.16205863 -0.59162673 -0.13950288  0.46799897  0.9523419 ]
 [-1.02098302  0.42447985 -0.44718963  0.33623429  1.16785186]
 [ 0.34360369 -0.19537749 -0.32067728 -0.12589691  0.15467134]]
[[-0.06160484 -0.16063992]
 [-0.15447482 -0.26389604]
 [-0.01831633  0.04863493]]
