<a href="https://colab.research.google.com/github/gmayank9999/DeepLearning/blob/main/Neural_Networks_from_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
# single neuron with 3 inputs
inputs=[1,2,3]
weights=[0.2,0.8,-0.5]
bias=2

output=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+bias
output

2.3

In [26]:
# 3 neurons
# 4 inputs to each neuron with 3 different list of weights
# 3 different bias
#bias and weights are with respect to neuron
inputs=[1,2,3,2.5]

weights1=[0.2,0.8,-0.5,1.0]
weights2=[0.5,-0.91,0.26,-0.5]
weights3=[-0.26,-0.27,0.17,0.87]

bias1=2
bias2=3
bias3=0.5

output=[inputs[0]*weights1[0]+inputs[1]*weights1[1]+inputs[2]*weights1[2]+inputs[3]*weights1[3]+bias1,
        inputs[0]*weights2[0]+inputs[1]*weights2[1]+inputs[2]*weights2[2]+inputs[3]*weights2[3]+bias2,
        inputs[0]*weights3[0]+inputs[1]*weights3[1]+inputs[2]*weights3[2]+inputs[3]*weights3[3]+bias3]
output

#by tweaking the weights and the bias, we can change the output
# hence in deep learning our job is how best to tune the weights and biases

[4.8, 1.21, 2.385]

In [1]:
inputs=[1,2,3,2.5]

weights=[[0.2,0.8,-0.5,1.0],
        [0.5,-0.91,0.26,-0.5],
        [-0.26,-0.27,0.17,0.87]]

biases=[2,3,0.5]

layer_outputs=[]
for neuron_weights,neuron_bias in zip(weights,biases):
    neuron_output=0
    for n_input,weight in zip(inputs,neuron_weights):
      neuron_output+=n_input*weight
    neuron_output+=neuron_bias
    layer_outputs.append(neuron_output)

print(layer_outputs )

[4.8, 1.21, 2.385]


In [3]:
import numpy as np
inputs=[1,2,3,2.5]
weights=[0.2,0.8,-0.5,1.0]
bias=2

output=np.dot(weights,inputs)+bias
print(output)

4.8


In [4]:
import numpy as np
inputs=[1,2,3,2.5]
weights=[[0.2,0.8,-0.5,1.0],
        [0.5,-0.91,0.26,-0.5],
        [-0.26,-0.27,0.17,0.87]]
biases=[2,3,0.5]

output=np.dot(weights,inputs)+biases
print(output)

[4.8   1.21  2.385]


In [4]:
#taking batches of inputs
import numpy as np
inputs=[[1,2,3,2.5],
        [2,5,-1,2],
        [-1.5,2.7,3.3,-0.8]]

weights=[[0.2,0.8,-0.5,1.0],
        [0.5,-0.91,0.26,-0.5],
        [-0.26,-0.27,0.17,0.87]]
biases=[2,3,0.5]

output=np.dot(inputs,np.array(weights).T)+biases
print(output)


[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [6]:
#Working with 2 layers
import numpy as np
inputs=[[1,2,3,2.5],
        [2,5,-1,2],
        [-1.5,2.7,3.3,-0.8]]

weights=[[0.2,0.8,-0.5,1.0],
        [0.5,-0.91,0.26,-0.5],
        [-0.26,-0.27,0.17,0.87]]
biases=[2,3,0.5]

weights2=[[0.1,-0.14,0.5],
        [-0.5,0.12,-0.33],
        [-0.44,0.73,-0.13]]
biases2=[-1,2,-0.5]

layer1_output=np.dot(inputs,np.array(weights).T)+biases
layer2_output=np.dot(layer1_output,np.array(weights2).T)+biases2
print(layer2_output)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [10]:
import numpy as np
# X is the input feature
X=[[1,2,3,2.5],
    [2,5,-1,2],
    [-1.5,2.7,3.3,-0.8]]

class Layer_Dense:
  def __init__(self,n_inputs,n_neurons):
     self.weights=0.10*np.random.randn(n_inputs,n_neurons)
     self.biases=np.zeros((1,n_neurons))
  def forward(self,inputs):
      self.output=np.dot(inputs,self.weights)+self.biases

layer1=Layer_Dense(4,5)
layer2=Layer_Dense(5,2)

layer1.forward(X)
print(layer1.output)

layer2.forward(layer1.output)
print(layer2.output)

[[-0.16205863 -0.59162673 -0.13950288  0.46799897  0.9523419 ]
 [-1.02098302  0.42447985 -0.44718963  0.33623429  1.16785186]
 [ 0.34360369 -0.19537749 -0.32067728 -0.12589691  0.15467134]]
[[-0.06160484 -0.16063992]
 [-0.15447482 -0.26389604]
 [-0.01831633  0.04863493]]


In [11]:
pip install nnfs

In [14]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()
X, y = spiral_data(100, 3)

class Layer_Dense:
  def __init__(self,n_inputs,n_neurons):
     self.weights=0.10*np.random.randn(n_inputs,n_neurons)
     self.biases=np.zeros((1,n_neurons))
  def forward(self,inputs):
      self.output=np.dot(inputs,self.weights)+self.biases

class Activation_ReLU:
  def forward(self,inputs):
    self.output=np.maximum(0,inputs)

layer1 = Layer_Dense(2,5)
activation1 = Activation_ReLU()
layer1.forward(X)
print(layer1.output)
print("="*100)
activation1.forward(layer1.output)
print(activation1.output)


[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [-8.35815910e-04 -7.90404272e-04 -1.33452227e-03  4.65504505e-04
   4.56846210e-05]
 [-2.39994470e-03  5.93469958e-05 -2.24808278e-03  2.03573116e-04
   6.10024377e-04]
 ...
 [ 1.13291524e-01 -1.89262271e-01 -2.06855070e-02  8.11079666e-02
  -6.71350807e-02]
 [ 1.34588361e-01 -1.43197834e-01  3.09493970e-02  5.66337556e-02
  -6.29687458e-02]
 [ 1.07817926e-01 -2.00809643e-01 -3.37579325e-02  8.72561932e-02
  -6.81458861e-02]]
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 4.65504505e-04
  4.56846210e-05]
 [0.00000000e+00 5.93469958e-05 0.00000000e+00 2.03573116e-04
  6.10024377e-04]
 ...
 [1.13291524e-01 0.00000000e+00 0.00000000e+00 8.11079666e-02
  0.00000000e+00]
 [1.34588361e-01 0.00000000e+00 3.09493970e-02 5.66337556e-02
  0.00000000e+00]
 [1.07817926e-01 0.00000000e+00 0.00000000e+00 8.72561932e-02
  0.00000000e+00]

In [17]:
#Input--> Exponentiate --> Normalise --> Output
#Softmax Activation =Exponentiate + Normalise
import numpy as np
# import math

layer_outputs=[4.8,1.21,2.385]
# E=math.e  # E is euler's number =2.7128.....

exp_values=np.exp(layer_outputs)
print(exp_values)

norm_values=exp_values/np.sum(exp_values)
print(norm_values)
print(np.sum(norm_values))

[121.51041752   3.35348465  10.85906266]
[0.89528266 0.02470831 0.08000903]
0.9999999999999999


In [20]:
#Input--> Exponentiate --> Normalise --> Output
#Softmax Activation =Exponentiate + Normalise
#input in batches
layer_outputs=[[4.8,1.21,2.385],
               [8.9,-1.81,0.2],
               [1.41,1.051,0.026]]

exp_values=np.exp(layer_outputs)

# print(np.sum(exp_values,axis=1,keepdims=True))   #axis=0 gives the sum of columns while axis=1 gives the sum of rows which is what we want
norm_values=exp_values/np.sum(exp_values,axis=1,keepdims=True)
print(norm_values)

#Note--> e to the power a large number can lead to overflow error, hence we should subtract the maximum value from all the data points, this will cause no change to the o/p but will protect from the overflow

[[8.95282664e-01 2.47083068e-02 8.00090293e-02]
 [9.99811129e-01 2.23163963e-05 1.66554348e-04]
 [5.13097164e-01 3.58333899e-01 1.28568936e-01]]


In [22]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data


class Layer_Dense:
  def __init__(self,n_inputs,n_neurons):
     self.weights=0.10*np.random.randn(n_inputs,n_neurons)
     self.biases=np.zeros((1,n_neurons))
  def forward(self,inputs):
      self.output=np.dot(inputs,self.weights)+self.biases

class Activation_ReLU:
  def forward(self,inputs):
    self.output=np.maximum(0,inputs)

class Activation_Softmax:
  def forward(self,inputs):
    exp_values=np.exp(inputs-np.max(inputs,axis=1,keepdims=True))
    probabilities=exp_values/np.sum(exp_values,axis=1,keepdims=True)
    self.output=probabilities


X,y=spiral_data(samples=100,classes=3)
dense1=Layer_Dense(2,3)
activation1=Activation_ReLU()

dense2=Layer_Dense(3,3)
activation2=Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)
dense2.forward(activation1.output)
activation2.forward(dense2.output)
print(activation2.output)


[[0.33333334 0.33333334 0.33333334]
 [0.33343706 0.33330157 0.3332613 ]
 [0.3334363  0.33340448 0.33315927]
 [0.33363777 0.33325708 0.33310518]
 [0.3337197  0.3332725  0.33300784]
 [0.33385548 0.33316278 0.33298174]
 [0.33386868 0.33331236 0.332819  ]
 [0.33375522 0.3335306  0.33271414]
 [0.33401015 0.33335492 0.33263496]
 [0.33405906 0.33340126 0.33253965]
 [0.3336788  0.33381182 0.33250934]
 [0.33424297 0.33338907 0.33236796]
 [0.3335921  0.33400425 0.3324037 ]
 [0.33351466 0.3340755  0.33240986]
 [0.33349293 0.33398643 0.3325206 ]
 [0.33355233 0.33423045 0.33221728]
 [0.33348194 0.33394113 0.33257693]
 [0.3335034  0.33402932 0.33246726]
 [0.33375525 0.33431962 0.3319251 ]
 [0.33379802 0.33436286 0.3318391 ]
 [0.3335962  0.3344112  0.33199257]
 [0.33343923 0.3337662  0.33279458]
 [0.33356425 0.33427945 0.3321563 ]
 [0.33360928 0.33446512 0.3319256 ]
 [0.33333334 0.33333334 0.33333334]
 [0.333448   0.33380195 0.3327501 ]
 [0.33371174 0.3348888  0.3313994 ]
 [0.33337337 0.3334967  0.33