<a href="https://colab.research.google.com/github/gmayank9999/DeepLearning/blob/main/Tensors_in_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

2.9.0+cu126


In [4]:
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))
else:
  print("CPU")

Tesla T4


## Creating a Tensor

In [6]:
a=torch.empty(2,3)
a

tensor([[1.5527e+20, 4.5311e-41, 1.5527e+20],
        [4.5311e-41, 6.3447e+31, 3.3509e+03]])

In [7]:
type(a)

torch.Tensor

In [8]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
torch.rand(2,3)

tensor([[0.5762, 0.3126, 0.4473],
        [0.9459, 0.8363, 0.4033]])

In [12]:
torch.rand(2,3)

tensor([[0.9173, 0.3633, 0.4973],
        [0.9162, 0.0012, 0.9780]])

In [13]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [14]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [16]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [19]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
x.shape

torch.Size([2, 3])

In [21]:
torch.empty_like(x)

tensor([[   845239872,    721791424, 489626271855],
        [446676598883, 489626271790, 472446402657]])

In [22]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [23]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [25]:
# torch.rand_like(x)
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Data Types

In [26]:
x.dtype

torch.int64

In [27]:
torch.tensor([1.0,2.0],dtype=torch.int32)

tensor([1, 2], dtype=torch.int32)

In [28]:
torch.tensor([[1,2,3,4],[10,21,121,1]],dtype=torch.float64)

tensor([[  1.,   2.,   3.,   4.],
        [ 10.,  21., 121.,   1.]], dtype=torch.float64)

In [41]:
x=torch.tensor([[10,20,30],[40,50,60]])
x

tensor([[10, 20, 30],
        [40, 50, 60]])

In [43]:
x.to(torch.float32)

tensor([[10., 20., 30.],
        [40., 50., 60.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# Mathematical Operations

In [44]:
x=torch.rand(2,2)
x

tensor([[0.7909, 0.4235],
        [0.0169, 0.2209]])

In [45]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[6.2550e-01, 1.7934e-01],
        [2.8558e-04, 4.8794e-02]])

In [46]:
p=torch.rand(2,3)
q=torch.rand(2,3)


In [47]:
p

tensor([[0.9535, 0.7064, 0.1629],
        [0.8902, 0.5163, 0.0359]])

In [48]:
q

tensor([[0.6476, 0.3430, 0.3182],
        [0.5261, 0.0447, 0.5123]])

In [49]:
# add
p+q
# sub
p-q
# multiply
p*q
# division
p/q
# power
p**q
# mod
p%q

tensor([[0.3059, 0.0204, 0.1629],
        [0.3641, 0.0250, 0.0359]])

In [50]:
r=torch.tensor([1,-2,3,-4])

In [51]:
torch.abs(r)

tensor([1, 2, 3, 4])

In [52]:
torch.neg(r)

tensor([-1,  2, -3,  4])

In [54]:
s=torch.tensor([1.9,2.3,3.7,11])
s

tensor([ 1.9000,  2.3000,  3.7000, 11.0000])

In [55]:
torch.round(s)

tensor([ 2.,  2.,  4., 11.])

In [56]:
torch.ceil(s)

tensor([ 2.,  3.,  4., 11.])

In [57]:
torch.floor(s)

tensor([ 1.,  2.,  3., 11.])

In [58]:
torch.clamp(s,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

In [60]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[8., 9., 7.],
        [9., 2., 6.]])

In [62]:
torch.sum(e)

tensor(41.)

In [63]:
torch.sum(e,dim=0)  #sum along columns

tensor([17., 11., 13.])

In [64]:
torch.sum(e,dim=1) #sum along rows

tensor([24., 17.])

In [65]:
torch.mean(e)

tensor(6.8333)

In [66]:
torch.mean(e,dim=0)

tensor([8.5000, 5.5000, 6.5000])

In [67]:
torch.median(e)

tensor(7.)

In [68]:
torch.max(e)

tensor(9.)

In [69]:
torch.min(e)

tensor(2.)

In [70]:
torch.prod(e)

tensor(54432.)

In [71]:
torch.std(e) # std deviation

tensor(2.6394)

In [72]:
torch.var(e)

tensor(6.9667)

In [73]:
torch.argmax(e)

tensor(1)

In [74]:
torch.argmin(e)

tensor(4)

In [76]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)
print(f)
print(g)

tensor([[7, 7, 8],
        [3, 6, 1]])
tensor([[5, 5],
        [0, 4],
        [3, 8]])


In [77]:
torch.matmul(f,g) #matrix multiplication

tensor([[ 59, 127],
        [ 18,  47]])

In [78]:
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])

In [79]:
#dot product
torch.dot(vector1,vector2)

tensor(11)

In [80]:
#transpose
torch.transpose(f,0,1)

tensor([[7, 3],
        [7, 6],
        [8, 1]])

In [81]:
h=torch.randint(size=(3,3),high=10,low=0,dtype=torch.float32)
h

tensor([[8., 3., 3.],
        [5., 0., 6.],
        [4., 0., 8.]])

In [82]:
torch.det(h)  # determinant

tensor(-48.)

In [83]:
torch.inverse(h)

tensor([[ 0.0000e+00,  5.0000e-01, -3.7500e-01],
        [ 3.3333e-01, -1.0833e+00,  6.8750e-01],
        [ 4.5155e-09, -2.5000e-01,  3.1250e-01]])

In [12]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[8, 4, 5],
        [4, 6, 8]])
tensor([[8, 4, 5],
        [9, 4, 6]])


In [13]:
# greater than
i > j

tensor([[False, False, False],
        [False,  True,  True]])

In [14]:
i<j

tensor([[False, False, False],
        [ True, False, False]])

In [15]:
i==j

tensor([[ True,  True,  True],
        [False, False, False]])

In [16]:
i!=j

tensor([[False, False, False],
        [ True,  True,  True]])

In [17]:
i>=j

tensor([[ True,  True,  True],
        [False,  True,  True]])

In [18]:
i<=j

tensor([[ True,  True,  True],
        [ True, False, False]])

In [19]:
k=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[8., 2., 1.],
        [5., 7., 5.]])

In [20]:
torch.log(k)

tensor([[2.0794, 0.6931, 0.0000],
        [1.6094, 1.9459, 1.6094]])

In [21]:
torch.exp(k)

tensor([[2.9810e+03, 7.3891e+00, 2.7183e+00],
        [1.4841e+02, 1.0966e+03, 1.4841e+02]])

In [22]:
torch.sqrt(k)

tensor([[2.8284, 1.4142, 1.0000],
        [2.2361, 2.6458, 2.2361]])

In [23]:
torch.sigmoid(k)

tensor([[0.9997, 0.8808, 0.7311],
        [0.9933, 0.9991, 0.9933]])

In [25]:
torch.softmax(k,dim=0)

tensor([[0.9526, 0.0067, 0.0180],
        [0.0474, 0.9933, 0.9820]])

In [26]:
torch.relu(k)

tensor([[8., 2., 1.],
        [5., 7., 5.]])

In [35]:
#inplace operation
m=torch.rand(2,3)
n=torch.rand(2,3)
print(m)
print(n)
print("="*50)
print(m.add_(n))
print(m)

print("="*50)
print(torch.relu(m))
print(m)
m.relu_()
print(m)

tensor([[0.4937, 0.2262, 0.4295],
        [0.9875, 0.6013, 0.0254]])
tensor([[0.9247, 0.9248, 0.8331],
        [0.7326, 0.4552, 0.6741]])
tensor([[1.4184, 1.1510, 1.2626],
        [1.7201, 1.0565, 0.6995]])
tensor([[1.4184, 1.1510, 1.2626],
        [1.7201, 1.0565, 0.6995]])
tensor([[1.4184, 1.1510, 1.2626],
        [1.7201, 1.0565, 0.6995]])
tensor([[1.4184, 1.1510, 1.2626],
        [1.7201, 1.0565, 0.6995]])
tensor([[1.4184, 1.1510, 1.2626],
        [1.7201, 1.0565, 0.6995]])


# Copying a Tensor

In [38]:
a=torch.rand(2,3)
a

tensor([[0.4281, 0.3253, 0.8262],
        [0.1970, 0.2978, 0.1601]])

In [39]:
b=a #not ideal way instead use clone method

In [40]:
b

tensor([[0.4281, 0.3253, 0.8262],
        [0.1970, 0.2978, 0.1601]])

In [41]:
a[0][0]=-1

In [42]:
print(a)
print(b)

tensor([[-1.0000,  0.3253,  0.8262],
        [ 0.1970,  0.2978,  0.1601]])
tensor([[-1.0000,  0.3253,  0.8262],
        [ 0.1970,  0.2978,  0.1601]])


In [43]:
print(id(a))
print(id(b))

133624660177488
133624660177488


In [45]:
b=a.clone()

In [46]:
print(a)
print(b)

tensor([[-1.0000,  0.3253,  0.8262],
        [ 0.1970,  0.2978,  0.1601]])
tensor([[-1.0000,  0.3253,  0.8262],
        [ 0.1970,  0.2978,  0.1601]])


In [47]:
a[0][0]=100

In [48]:
print(a)
print(b)

tensor([[100.0000,   0.3253,   0.8262],
        [  0.1970,   0.2978,   0.1601]])
tensor([[-1.0000,  0.3253,  0.8262],
        [ 0.1970,  0.2978,  0.1601]])


# Tensor Operations on GPU

In [3]:
torch.cuda.is_available()

True

In [4]:
device=torch.device('cuda')

In [5]:
#creating a new tensor on GPU
torch.rand(size=(2,3),device=device)

tensor([[0.8930, 0.5412, 0.7811],
        [0.4617, 0.5998, 0.6622]], device='cuda:0')

In [6]:
a=torch.rand(2,3)
a
# a is on cpu currently

tensor([[0.4847, 0.2865, 0.9806],
        [0.1765, 0.6616, 0.3321]])

In [9]:
b=a.to(device)  #move an existing tensor to gpu
b


tensor([[0.4847, 0.2865, 0.9806],
        [0.1765, 0.6616, 0.3321]], device='cuda:0')

# Reshaping Tensors

In [11]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [13]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
b=torch.rand(2,3,4)
b

tensor([[[0.3545, 0.5323, 0.1031, 0.9335],
         [0.1076, 0.5265, 0.6980, 0.8382],
         [0.1580, 0.1330, 0.1137, 0.0951]],

        [[0.6728, 0.0249, 0.5312, 0.9699],
         [0.3377, 0.9731, 0.1440, 0.9141],
         [0.1206, 0.9082, 0.4758, 0.4874]]])

In [17]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [18]:
#unsqueeze
#it adds a new dimension
c=torch.rand(226,226,3)
c.unsqueeze(0).shape # unsqueeze adds a new dimension to whatever position you pass in the argument



torch.Size([1, 226, 226, 3])

In [23]:
# squeeze (just opposite of unsqueeze)
d=torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

# Numpy and Torch

In [25]:
import numpy as np

In [26]:
a=torch.tensor([1,2,3])

In [28]:
b=a.numpy() # convert tensor a to numpy array
b

array([1, 2, 3])

In [29]:
type(b)

numpy.ndarray

In [32]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [34]:
torch.from_numpy(c)   # convert numpy array to tensor

tensor([1, 2, 3])